version: 5.0.0.{build}

configuration: Release

image: Visual Studio 2017

platform: Any CPU

environment:
  SECRET_FOR_TEST_CONFIG: 
    secure: yoweGR1iLIk+/QjhT19L4p+HHUnusMIxY55iKHxiwo4=
  ENCRYPTED_GITHUB_TOKEN: 
    secure: Reyav3mZ2+GrP95jo8SMJbYRiCsdtSq8a9rvniYZr7s2e1vUVpENSQ7ixboRFQlG
  GITHUB_EMAIL: marfachaiko@gmail.com

before_build:

- cmd: >-

    nuget restore SDK\Source\Virgil.SDK.sln

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt SDK\Source\Virgil.SDK.Tests.Win\App.config.enc -secret %SECRET_FOR_TEST_CONFIG%

    secure-file\tools\secure-file -decrypt SDK\Source\Virgil.SDK.Tests.Win\crypto_compatibility_data.json.enc -secret %SECRET_FOR_TEST_CONFIG% -out C:\projects\virgil-sdk-net\crypto_compatibility_data.json
    
    msbuild SDK\Source\Virgil.SDK.Std\Virgil.SDK.Std.csproj
build:

  project: SDK\Source\Virgil.SDK.Tests.Win\Virgil.SDK.Tests.Win.csproj
  verbosity: minimal

test_script:
- cmd: nunit3-console SDK\Source\Virgil.SDK.Tests.Win\bin\Release\Virgil.SDK.Tests.Win.dll --result=myresults.xml;format=AppVeyor

deploy: on